config/routes.rb
Rails.application.routes.draw do
  root :to => 'products#home'


  resources :products do
    resources :reviews, :except => [:show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
 has_many :reviews
accepts_nested_attributes_for :reviews

 scope :three_most_recent, -> { order(created_at: :desc).limit(3)}
 scope(:us_product, -> do
  where({:country_of_origin => "United States"})
end)

scope :most_reviews, -> {(
  select("products.id, products.name, count(reviews.id) as reviews_count")
  .joins(:reviews)
  .group("products.id")
  .order("reviews_count DESC")
  .limit(1)
  )}


 validates :name, :presence => true
 validates :cost, :presence => true
 validates :country_of_origin, :presence => true
end

app/models/review.rb
class Review < ActiveRecord::Base
 belongs_to :product, optional: true

 validates :author, :presence => true
 validates :content_body, :presence => true, length: { in: 50..250 }

 validates :rating, :presence => true, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  def home
    @products = Product.three_most_recent
    @us_products = Product.us_product
    @most_review_product = Product.most_reviews

  end
  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
    render :edit
    end
  end



  def create
  @product = Product.new(product_params)
  if @product.save

    #redirect to individual product item
    redirect_to  product_path(@product)

    #redirect to the products page
    # redirect_to  products_path
  else

    render :new
  end
end



  private

  def product_params
    params.require(:product).permit(:name, :country_of_origin, :cost)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      redirect_to product_path(@review.product)
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to product_path(@review.product)
      # redirect_to  product_path(@product)
    else
      render :edit
    end
  end



  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to product_path(@review.product)
  end


private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarioFood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">

 <!-- flash[:alert]
flash[:notice]  -->
<!-- erb tags -->

    <%= yield %>
    <div class="footer">
      <%= link_to "Home Page", "/"  %>
      <%= link_to "All Products", products_path %>
    </div>


  </div>

  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :country_of_origin %>
  <%= f.text_field :country_of_origin %>
  <%= f.label :cost %>
  <%= f.number_field :cost, :step => 0.01 %>
  <%= f.submit %>
<% end %>

app/views/products/home.html.erb
<h1>Mario's food yelp place</h1>

<p class="about">
  Mario is a great man that sells great food.  See what people think of the different products sold at Mario's.  Also add a review yourself.  Just click on All Products to get started.
</p>
<div class="three-most-recent">

<h3>The three most recently added products to the store. From most recent to third-most-recent</h3>

<ol>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ol>
</div>
<div class="america">

<h3>All Products with a county of origin of "United States"</h3>

<ul>
  <% @us_products.each do |us_product| %>
  <li><%= link_to us_product.name, product_path(us_product) %></li>
  <% end %>
</ul>
</div>
<div class="discount">
  <p>Refer a Friend. Earn 10% off Meat Products!</p>

</div>

<h3>The Products with the most reviews</h3>
<div class="most_review_product">

<% @most_review_product.each do |product| %>
<ul>


<li><%= link_to product.name, product_path(product)%></li>
<% end %>
</ul>
</div>



<div class="gallery">
  <img class="left" src="assets/shopper1.jpeg" alt="shopper1">
  <img class="left" src="assets/shopper2.jpeg" alt="shopper1">
  <img class="right" src="assets/shopper3.jpeg" alt="shopper1">
  <img class="right" src="assets/shopper4.jpeg" alt="shopper1">
  <img class="mid" src="assets/shopper5.jpeg" alt="shopper1">
  <img class="mid" src="assets/shopper6.jpeg" alt="shopper1">

</div>

app/views/products/index.html.erb
<h1>Products</h1>
<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>

<p><%= link_to "New product", new_product_path %></p>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form" %>

app/views/products/show.html.erb
<h1>  <%= @product.name %> </h1>
<h2><%= @product.country_of_origin %></h2>
<h3>$<%= @product.cost %></h3>
<h4><%= @product.id %></h4>

<% if @product.reviews.any? %>
  <h4>Here are the reviews for this product:</h4>


  <ul>
    <% @product.reviews.each do |review| %>
      <li>
        <%= review.author %> |
        <%= review.content_body %> |
        <%= review.rating %>
        <hr>
        <%= link_to "Edit", edit_product_review_path(@product, review) %> |
        <%= link_to "Delete", product_review_path(@product, review),
                                 :data => {:confirm => "Are you sure?",
                                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no reviews yet!</p>
<% end %>

<p><%= link_to "Add a review", new_product_review_path(@product) %></p>
<p><%= link_to "Delete Product", product_path(@product),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>

<p><%= link_to "Edit this Product", edit_product_path(@product) %></p>

<p><%= link_to "Return to products", products_path %></p>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <%= f.label :content_body %>
  <%= f.text_field :content_body %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit review</h1>


<%= render "form" %>

app/views/reviews/new.html.erb
<h1>New review for <%= @product.name %></h1>

<%= render 'form' %>